export const DUMMY_DATA = [
  {
    title: "Section 1",
    isSection: true,
    level: 1,
    id: 1,
    parent: null,
  },
  {
    title: "Subsection 1.1",
    isSection: true,
    level: 2,
    id: 2,
    parent: 1,
  },
  {
    title: "Content for Subsection 1.1",
    isSection: false,
    level: 3,
    id: 3,
    parent: 2,
  },
  {
    title: "Subsection 1.2",
    isSection: true,
    level: 2,
    id: 4,
    parent: 1,
  },
  {
    title: "Content for Subsection 1.2",
    isSection: false,
    level: 3,
    id: 5,
    parent: 4,
  },
  {
    title: "Subsection 1.2.1",
    isSection: true,
    level: 3,
    id: 6,
    parent: 4,
  },
  {
    title: "Content for Subsection 1.2.1",
    isSection: false,
    level: 4,
    id: 7,
    parent: 6,
  },
  {
    title: "Content for Subsection 1.2 (1)",
    isSection: false,
    level: 3,
    id: 8,
    parent: 4,
  },
  {
    title: "Section 2",
    isSection: true,
    level: 1,
    id: 9,
    parent: null,
  },
  {
    title: "Content for Section 2",
    isSection: false,
    level: 2,
    id: 10,
    parent: 9,
  },
  {
    title: "Content for individual item",
    isSection: false,
    level: 1,
    id: 11,
    parent: null,
  },
];
